ALTER TABLE courses
    ADD COLUMN IF NOT EXISTS status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' AFTER category,
    ADD COLUMN IF NOT EXISTS semester_label VARCHAR(128) NULL AFTER teacher,
    ADD COLUMN IF NOT EXISTS archived_at DATETIME NULL AFTER updated_at;
